@startuml
title Command Flow

UI --> ApplicationService : UI input data
ApplicationService --> CommandHandler : CommandPayload
CommandHandler --> Command : CommandPayload
Command --> Aggregate : raw values
Aggregate --> Command : AggregateEntity
Command --> CommandHandler : AggregateEntity
CommandHandler --> ApplicationService : AggregateEntity
ApplicationService --> Repository : AggregateEntity

@enduml
