@startuml
title Query Flow

UI --> ApplicationService : request input
ApplicationService --> QueryHandler : query params
QueryHandler --> Query : query params
Query --> Repository : query params
Repository --> Query : AggregateEntity
Query --> QueryHandler : AggregateEntity[]
QueryHandler --> Filter : AggregateEntity[]
Filter --> QueryHandler : AggregateEntity[]
QueryHandler --> ApplicationService : AggregateEntity[]
ApplicationService --> Store : AggregateEntity[]

@enduml
