services:
  thoughtless-fe:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    networks:
      - thoughtless
      - traefik_proxy
    labels:
      - "traefik.enable=true"

      # HTTP → HTTPS redirect
      - "traefik.http.routers.frontend-http.rule=Host(`thoughtless.grozdan.app`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"

      # Define redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # HTTPS router
      - "traefik.http.routers.frontend.rule=Host(`thoughtless.grozdan.app`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.routers.frontend.service=frontend-svc"

      # Service points to container’s internal port
      - "traefik.http.services.frontend-svc.loadbalancer.server.port=80"


networks:
  thoughtless:
    external: true
  traefik_proxy:
    external: true
