version: "3.9"

services:
  quasar:
    build:
      context: .
      dockerfile: ./docker/quasar/Dockerfile
    networks:
      - thoughtless
      - traefik_proxy
    labels:
      - "traefik.enable=true"

      # HTTPS
      - "traefik.http.routers.frontend.rule=Host(`thoughtless.grozdan.app`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"

      # HTTP → HTTPS redirect
      - "traefik.http.middlewares.frontend-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.frontend-http.rule=Host(`thoughtless.grozdan.app`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=frontend-redirect"

networks:
  thoughtless:
    external: true
  traefik_proxy:
    external: true
