services:
  quasar:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: npx quasar dev --hostname 0.0.0.0 --port 9000
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST_UID=${UID:-1000}
    stdin_open: true
    tty: true
    networks:
      - thoughtless

networks:
  thoughtless:
    external: true
