# Project default compose file.
services:
  quasar:
    build: .
    container_name: thoughtless-app
    ports:
      - '9001:9001'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
