services:
  quasar:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST_UID=${UID:-1000}
    stdin_open: true
    tty: true
    networks:
      - thoughtless
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"

      # HTTPS
      - "traefik.http.routers.thoughtless.rule=Host(`thoughtless.grozdan.app`)"
      - "traefik.http.routers.thoughtless.entrypoints=websecure"
      - "traefik.http.routers.thoughtless.tls=true"
      - "traefik.http.routers.thoughtless.tls.certresolver=le"
      - "traefik.http.services.thoughtless.loadbalancer.server.port=9000"

      # HTTP -> HTTPS redirect
      - "traefik.http.routers.thoughtless-redirect.rule=Host(`thoughtless.grozdan.app`)"
      - "traefik.http.routers.thoughtless-redirect.entrypoints=web"
      - "traefik.http.routers.thoughtless-redirect.middlewares=redirect-https@docker"

networks:
  thoughtless:
    external: true
  traefik_proxy:
    external: true
