@startuml
title Boot Sequence

AppBoot --> RootBoot : runBootSequence()
RootBoot --> RootBooter : execute()
RootBooter --> PlatformBooter : execute()
RootBooter --> MicroserviceBooter : execute()
RootBoot --> RootRunner : execute()
RootRunner --> PlatformRunner : execute()
RootRunner --> MicroserviceRunner : execute()

@enduml
